package com.algo.trade.backtest.v2;

import com.algo.trade.domain.OptionType;
import com.algo.trade.strategy.StrategyType;

import java.time.Instant;

/**
 * Entry signal generated by a StrategyAdapter during snapshot-based backtesting.
 */
public record StrategySignal(
        Instant timestamp,
        StrategyType strategyType,
        OptionType optionType,
        int strike,
        double entryPrice,
        double spotPrice,
        String reason,
        double confidence,    // 0.0 to 1.0
        double iv,
        double delta,
        long oi,
        long volume
) {
    public StrategySignal {
        if (confidence < 0 || confidence > 1) {
            throw new IllegalArgumentException("Confidence must be between 0 and 1: " + confidence);
        }
    }
}
