package com.algo.trade.backtest.v2;

import java.time.Instant;

/**
 * Exit signal generated by a StrategyAdapter during snapshot-based backtesting.
 */
public record ExitSignal(
        Instant timestamp,
        double exitPrice,
        ExitReason reason,
        String detail
) {

    public enum ExitReason {
        STOP_LOSS,
        TARGET_HIT,
        TRAILING_STOP,
        TIME_BASED,
        SIGNAL_REVERSAL,
        END_OF_DAY,
        IV_CRUSH,
        DELTA_DECAY
    }
}
